stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - data/data.xml
    - src/prepare.py
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    outs:
    - data/features

  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features auc.metric
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - auc.metric:
        cache: false
